# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.1.1
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.trending_trending_category import TrendingTrendingCategory  # noqa: E501
from swagger_client.rest import ApiException


class TestTrendingTrendingCategory(unittest.TestCase):
    """TrendingTrendingCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrendingTrendingCategory(self):
        """Test TrendingTrendingCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.trending_trending_category.TrendingTrendingCategory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
