# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.1.1
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.preview_api import PreviewApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPreviewApi(unittest.TestCase):
    """PreviewApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.preview_api.PreviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_destiny2_activate_talent_node(self):
        """Test case for destiny2_activate_talent_node

        """
        pass

    def test_destiny2_get_clan_aggregate_stats(self):
        """Test case for destiny2_get_clan_aggregate_stats

        """
        pass

    def test_destiny2_get_clan_leaderboards(self):
        """Test case for destiny2_get_clan_leaderboards

        """
        pass

    def test_destiny2_get_leaderboards(self):
        """Test case for destiny2_get_leaderboards

        """
        pass

    def test_destiny2_get_leaderboards_for_character(self):
        """Test case for destiny2_get_leaderboards_for_character

        """
        pass

    def test_destiny2_get_vendor(self):
        """Test case for destiny2_get_vendor

        """
        pass

    def test_destiny2_get_vendors(self):
        """Test case for destiny2_get_vendors

        """
        pass

    def test_destiny2_insert_socket_plug(self):
        """Test case for destiny2_insert_socket_plug

        """
        pass


if __name__ == '__main__':
    unittest.main()
