# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.1.1
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.group_v2_api import GroupV2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupV2Api(unittest.TestCase):
    """GroupV2Api unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.group_v2_api.GroupV2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_group_v2_abdicate_foundership(self):
        """Test case for group_v2_abdicate_foundership

        """
        pass

    def test_group_v2_add_optional_conversation(self):
        """Test case for group_v2_add_optional_conversation

        """
        pass

    def test_group_v2_approve_all_pending(self):
        """Test case for group_v2_approve_all_pending

        """
        pass

    def test_group_v2_approve_pending(self):
        """Test case for group_v2_approve_pending

        """
        pass

    def test_group_v2_approve_pending_for_list(self):
        """Test case for group_v2_approve_pending_for_list

        """
        pass

    def test_group_v2_ban_member(self):
        """Test case for group_v2_ban_member

        """
        pass

    def test_group_v2_create_group(self):
        """Test case for group_v2_create_group

        """
        pass

    def test_group_v2_deny_all_pending(self):
        """Test case for group_v2_deny_all_pending

        """
        pass

    def test_group_v2_deny_pending_for_list(self):
        """Test case for group_v2_deny_pending_for_list

        """
        pass

    def test_group_v2_edit_clan_banner(self):
        """Test case for group_v2_edit_clan_banner

        """
        pass

    def test_group_v2_edit_founder_options(self):
        """Test case for group_v2_edit_founder_options

        """
        pass

    def test_group_v2_edit_group(self):
        """Test case for group_v2_edit_group

        """
        pass

    def test_group_v2_edit_group_membership(self):
        """Test case for group_v2_edit_group_membership

        """
        pass

    def test_group_v2_edit_optional_conversation(self):
        """Test case for group_v2_edit_optional_conversation

        """
        pass

    def test_group_v2_get_admins_and_founder_of_group(self):
        """Test case for group_v2_get_admins_and_founder_of_group

        """
        pass

    def test_group_v2_get_available_avatars(self):
        """Test case for group_v2_get_available_avatars

        """
        pass

    def test_group_v2_get_available_themes(self):
        """Test case for group_v2_get_available_themes

        """
        pass

    def test_group_v2_get_banned_members_of_group(self):
        """Test case for group_v2_get_banned_members_of_group

        """
        pass

    def test_group_v2_get_group(self):
        """Test case for group_v2_get_group

        """
        pass

    def test_group_v2_get_group_by_name(self):
        """Test case for group_v2_get_group_by_name

        """
        pass

    def test_group_v2_get_group_optional_conversations(self):
        """Test case for group_v2_get_group_optional_conversations

        """
        pass

    def test_group_v2_get_groups_for_member(self):
        """Test case for group_v2_get_groups_for_member

        """
        pass

    def test_group_v2_get_invited_individuals(self):
        """Test case for group_v2_get_invited_individuals

        """
        pass

    def test_group_v2_get_members_of_group(self):
        """Test case for group_v2_get_members_of_group

        """
        pass

    def test_group_v2_get_pending_memberships(self):
        """Test case for group_v2_get_pending_memberships

        """
        pass

    def test_group_v2_get_potential_groups_for_member(self):
        """Test case for group_v2_get_potential_groups_for_member

        """
        pass

    def test_group_v2_get_recommended_groups(self):
        """Test case for group_v2_get_recommended_groups

        """
        pass

    def test_group_v2_get_user_clan_invite_setting(self):
        """Test case for group_v2_get_user_clan_invite_setting

        """
        pass

    def test_group_v2_group_search(self):
        """Test case for group_v2_group_search

        """
        pass

    def test_group_v2_individual_group_invite(self):
        """Test case for group_v2_individual_group_invite

        """
        pass

    def test_group_v2_individual_group_invite_cancel(self):
        """Test case for group_v2_individual_group_invite_cancel

        """
        pass

    def test_group_v2_kick_member(self):
        """Test case for group_v2_kick_member

        """
        pass

    def test_group_v2_request_group_membership(self):
        """Test case for group_v2_request_group_membership

        """
        pass

    def test_group_v2_rescind_group_membership(self):
        """Test case for group_v2_rescind_group_membership

        """
        pass

    def test_group_v2_set_user_clan_invite_setting(self):
        """Test case for group_v2_set_user_clan_invite_setting

        """
        pass

    def test_group_v2_unban_member(self):
        """Test case for group_v2_unban_member

        """
        pass


if __name__ == '__main__':
    unittest.main()
