# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_30 import InlineResponse20030


class TestInlineResponse20030(unittest.TestCase):
    """ InlineResponse20030 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20030(self):
        """
        Test InlineResponse20030
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.inline_response_200_30.InlineResponse20030()
        pass


if __name__ == '__main__':
    unittest.main()
