# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.1.1
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.destiny_definitions_destiny_item_creation_entry_level_definition import DestinyDefinitionsDestinyItemCreationEntryLevelDefinition  # noqa: E501
from swagger_client.rest import ApiException


class TestDestinyDefinitionsDestinyItemCreationEntryLevelDefinition(unittest.TestCase):
    """DestinyDefinitionsDestinyItemCreationEntryLevelDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinyDefinitionsDestinyItemCreationEntryLevelDefinition(self):
        """Test DestinyDefinitionsDestinyItemCreationEntryLevelDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.destiny_definitions_destiny_item_creation_entry_level_definition.DestinyDefinitionsDestinyItemCreationEntryLevelDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
