# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.  # noqa: E501

    OpenAPI spec version: 2.1.1
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.destiny_historical_stats_destiny_historical_stats_value import DestinyHistoricalStatsDestinyHistoricalStatsValue  # noqa: F401,E501


class DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'period': 'datetime',
        'activity_details': 'object',
        'values': 'dict(str, DestinyHistoricalStatsDestinyHistoricalStatsValue)'
    }

    attribute_map = {
        'period': 'period',
        'activity_details': 'activityDetails',
        'values': 'values'
    }

    def __init__(self, period=None, activity_details=None, values=None):  # noqa: E501
        """DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup - a model defined in Swagger"""  # noqa: E501

        self._period = None
        self._activity_details = None
        self._values = None
        self.discriminator = None

        if period is not None:
            self.period = period
        if activity_details is not None:
            self.activity_details = activity_details
        if values is not None:
            self.values = values

    @property
    def period(self):
        """Gets the period of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501

        Period for the group. If the stat periodType is day, then this will have a specific day. If the type is monthly, then this value will be the first day of the applicable month. This value is not set when the periodType is 'all time'.  # noqa: E501

        :return: The period of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501
        :rtype: datetime
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.

        Period for the group. If the stat periodType is day, then this will have a specific day. If the type is monthly, then this value will be the first day of the applicable month. This value is not set when the periodType is 'all time'.  # noqa: E501

        :param period: The period of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501
        :type: datetime
        """

        self._period = period

    @property
    def activity_details(self):
        """Gets the activity_details of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501

        If the period group is for a specific activity, this property will be set.  # noqa: E501

        :return: The activity_details of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501
        :rtype: object
        """
        return self._activity_details

    @activity_details.setter
    def activity_details(self, activity_details):
        """Sets the activity_details of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.

        If the period group is for a specific activity, this property will be set.  # noqa: E501

        :param activity_details: The activity_details of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501
        :type: object
        """

        self._activity_details = activity_details

    @property
    def values(self):
        """Gets the values of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501

        Collection of stats for the period.  # noqa: E501

        :return: The values of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501
        :rtype: dict(str, DestinyHistoricalStatsDestinyHistoricalStatsValue)
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.

        Collection of stats for the period.  # noqa: E501

        :param values: The values of this DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup.  # noqa: E501
        :type: dict(str, DestinyHistoricalStatsDestinyHistoricalStatsValue)
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
